FROM node:14.15-alpine

WORKDIR /app
COPY . .

RUN npm ci --production\
    && cd ./client \
    && npm ci --production \
    && npm run build \
    && rm -rf ./node_modules \
    && rm -rf ./src

ENV NODE_ENV=production
EXPOSE 7000

CMD ["npm", "start"]
