export const ADD_SUCCESS_NOTIFICATION = 'ADD_SUCCESS_NOTIFICATION';
export const ADD_ERROR_NOTIFICATION = 'ADD_ERROR_NOTIFICATION';

export const REMOVE_SUCCESS_NOTIFICATION = 'REMOVE_SUCCESS_NOTIFICATION';
export const REMOVE_ERROR_NOTIFICATION = 'REMOVE_ERROR_NOTIFICATION';
